### ISSUE TITLE
xcode6  not support now ?

### ISSUE THREAD

**Issue by nonstriater** [macoscope/CodePilot#18]

**Comment by esttorhe** [comment]
@macoscopehq is this project :skull: :grey_question: 

Just wondering since the original PR was never merged and now its "useless" for `Xcode 6.2`.

Tried a quick update on my end but it will required a major overhaul because the project needs to be migrated to `ARC` and looks like it will take some more effort than just changing the `UUID`.

Would love to help with the project (I can take some time and migrate it to `ARC` but not if the project is dead and there won't be a merge happening any time soon).

I can offer myself as a contributor if you guys would like some helping :open_hands:

**Comment by watermeion** [comment]
@esttorhe  
xcode6.2 cannot use Codepilot ? I need some help !

**Comment by justMaku** [comment]
@esttorhe 
Thanks for the offer! We will see about that ;) 


That's true that we have shifted our focus in a little bit different direction after the initial release, but we are here now to correct the mistakes of the past. From now on I personally will be responsible for this repository, and if ever there's any stagnation going on, feel free to tag me in the issue/PR.

As for the XCode 6.2 support: it's happening for sure, but I can't be specific on the actual release date. We will keep you all updated within issue #24 , so please stick arround.

As for the contributions to the project: I will start going through the PR's today and see how we can get this baby rolling again.

**Comment by danipralea** [comment]
Great news !
I'm also waiting to see the update with a 6.2 support as well. I'm feeling so sorry that I cannot use CodePilot anymore :( It brought a huge difference when using it.

**Comment by justMaku** [comment]
XCode support has been added to the master branch.

**Comment by esttorhe** [comment]
Thanks @justMaku .

Offer still stands; if you need any help with the project just drop me a message
