### ISSUE TITLE
Xcode 7.x support

### ISSUE THREAD

**Issue by 7934345** [macoscope/CodePilot#59]
As Title, Thx and Plz.

**Comment by mingyue1991** [comment]
xcode 7.2 doesn't work. Don't support???

**Comment by bartekchlebek** [comment]
Should work as soon as #60 is merged. Thanks for the report! :clap:

**Comment by cgcsyao** [comment]
Version 7.2 (7C68) doesn't work. Try manual and alcatraz.

**Comment by ober01** [comment]
Version 7.2 doesn't work too

**Comment by 7934345** [comment]
7.3 is coming out.

**Comment by lakhman** [comment]
Im using 7.3, can confirm it doesn't work, really want to try this! it looks awesome.

**Comment by Bionik6** [comment]
It's working really well for me. Am currently using Xcode 7.3 and here are the tweaks I've made in order to get the plugin to work. 

1. Go to your plugins directory: CMD+SHIFT+G and enter the following path ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins
2. Locate the CodePilot3.xcplugin, right-click on it and select 'Show Package Content'
3. Edit the Info.plist file which is inside the Contents folder and add a value key to the _DVTPlugInCompatibilityUUIDs_ key. The value of the string is **ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C**
4. Save the file, quit and reopen XCode, then load the plugin in the prompt window.
5. That's it. You should now able to see the plugin option in File -> Code Pilot.

Hope it helps :)

**Comment by harryzjm** [comment]
@Bionik6 Thanks for you, now it work very well

**Comment by penguin-penpen** [comment]
Xcode 7.2.1. CodePilot is still not working after changing the `info.plist`. Tried manual and alcatraz. There's no `Load Bundle` window when reopening Xcode.

**Comment by bubski** [comment]
Should be fixed with #60
